version: "3"
services:
  php:
    image: phpcms.runtime:v1
    working_dir: /www
    volumes:
      - ./:/www
    networks:
      - mynet
  nginx:
    image: nginx:1.13.0-alpine
    ports:
      - "1414:80"
    depends_on:
      - php
    volumes:
      - ./__cicd__/nginx/:/etc/nginx/conf.d/
      - ./:/www
    networks:
      - mynet
networks:
  mynet:
volumes:
  mydir:
